---
- set_fact:
    binaries:
      - name: nifi binaries
        zip_url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.zip"
        sha256_url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-{{ nifi_version }}-bin.zip.sha256"
        zip_path: "{{ nifi_config_dirs.binaries }}/nifi-{{ nifi_version }}-bin.zip"
        dest_path: "{{ nifi_config_dirs.install }}/nifi-{{ nifi_version }}"
        dest_unarchive: "{{ nifi_config_dirs.install }}/"
        dest_symlink: "{{ nifi_config_dirs.home }}"

      - name: nifi toolkit binaries
        zip_url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-toolkit-{{ nifi_version }}-bin.zip"
        sha256_url: "{{ download_mirror_uri }}/nifi/{{ nifi_version }}/nifi-toolkit-{{ nifi_version }}-bin.zip.sha256"
        zip_path: "{{ nifi_config_dirs.binaries }}/nifi-toolkit-{{ nifi_version }}-bin.zip"
        dest_path: "{{ nifi_config_dirs.install }}/nifi-toolkit-{{ nifi_version }}"
        dest_unarchive: "{{ nifi_config_dirs.install }}"
        dest_symlink: "{{ nifi_config_dirs.home }}/toolkit"
  tags: [ download ]

- name: Downloading binaries
  ansible.builtin.include_tasks: download_item.yml
  with_items: "{{ binaries }}"
  tags: [ download ]

- name: Installing binaries
  ansible.builtin.include_tasks: install_item.yml
  with_items: "{{ binaries }}"