---
- name: Prepare system
  ansible.builtin.import_tasks: prepare.yml
  tags: [ prepare ]

- name: Install NiFi
  ansible.builtin.import_tasks: install.yml
  tags: [ install ]

- name: Init secrets
  ansible.builtin.import_tasks: secrets.yml
  tags: [ secrets]

- name: Customize NiFi
  ansible.builtin.import_tasks: customize.yml
  tags: [ config ]

- name: Add NiFi as system service
  ansible.builtin.import_tasks: systemd.yml
  tags: [ install ]

